Repository mcu-tools/mcuboot, pull requests merged in 2022-06, with the labels that each got.

#1349 boot: Check that hash TLV is sufficiently large
  boot/bootutil/src/boot_record.c
Labels: area: core

#1379 boot_serial: Fix echo command code no longer compiling
  boot/boot_serial/src/boot_serial.c
  boot/boot_serial/src/echo.cddl
  boot/boot_serial/src/serial_recovery_echo.c
  boot/boot_serial/src/serial_recovery_echo.h
  boot/boot_serial/src/serial_recovery_echo_types.h
  boot/zephyr/CMakeLists.txt
Labels: bug

#1395 Refactoring of erase and write operations in bs_upload
  boot/boot_serial/src/boot_serial.c
Labels: area: serial recovery
