Repository mcu-tools/mcuboot, pull requests merged in 2023-08, with the labels that each got.

#1764 nuttx: switch to flash_area_get_sector
  boot/nuttx/include/flash_map_backend/flash_map_backend.h
  boot/nuttx/src/flash_map_backend/flash_map_backend.c
Labels: area: nuttx

#1763 bootutil: Fix boot_set_next passing wrong image number
  boot/bootutil/src/bootutil_public.c
Labels: bug, area: core

#1771 bootutil: Fix for flash_area_id_to_image
  boot/bootutil/src/bootutil_public.c
Labels: Hotfix

#1757 bootutil: fix downgrade prevention bypass
  boot/bootutil/src/loader.c
Labels: bug, area: core

#1777 ci: mynewt: Update to install upstream Mbed-TLS
  ci/mynewt_install.sh
Labels: [DNM]

#1783 bootutil: Move flash_area_id_to_image under ifdef
  boot/bootutil/src/bootutil_public.c
Labels: Hotfix

#1787 zephyr: Fix boot serial extensions
  boot/zephyr/boot_serial_extensions.c
Labels: area: zephyr
