Repository mcu-tools/mcuboot, pull requests merged in 2023-02, with the labels that each got.

#1583 boot: zephyr: add support for RT595
  boot/zephyr/boards/mimxrt595_evk_cm33.conf
Labels: 1.10.0

#1586 Use full links for Cypress and Sim usage instructions
  docs/index.md
Labels: 1.10.0

#1563 flash_map_backend: Remove flash_area_id_to_image_slot
  boot/cypress/cy_flash_pal/cy_flash_map.c
  boot/cypress/cy_flash_pal/include/flash_map_backend/flash_map_backend.h
  boot/mbed/include/flash_map_backend/flash_map_backend.h
  boot/mbed/src/flash_map_backend.cpp
  boot/zephyr/flash_map_extended.c
  boot/zephyr/include/flash_map_backend/flash_map_backend.h
  sim/mcuboot-sys/csupport/storage/flash_map.h
Labels: area: core, 1.10.0

#1622 ci: Update TF-M version to be aligned with FIH library changes
  ci/fih-tests_run.sh
Labels: 1.10.0

#1600 bootutil: Move duplicate static inline functions to one header
  boot/bootutil/src/bootutil_misc.c
  boot/bootutil/src/bootutil_misc.h
  boot/bootutil/src/bootutil_public.c
Labels: 1.10.0

#1601 bootutil: Little rework of boot_find_status
  boot/bootutil/src/bootutil_misc.c
Labels: 1.10.0

#1602 bootutil: Pass flash_area to boot_read_swap_size
  boot/bootutil/src/bootutil_misc.c
  boot/bootutil/src/bootutil_priv.h
  boot/bootutil/src/loader.c
  boot/bootutil/src/swap_move.c
Labels: 1.10.0

#1578 loader.c: fill_rsp - Fix possible array index overflow - L1 CERT-C
  boot/bootutil/src/loader.c
Labels: 1.10.0

#1550 docs: zephyr: Add note on swap-using-scratch
  docs/readme-zephyr.md
Labels: area: zephyr, area: docs, 1.10.0
