Repository mcu-tools/mcuboot, pull requests merged in 2024-07, with the labels that each got.

#1996 Revert "boot: Add MCUBOOT_HW_KEY support for image encryption"
  boot/bootutil/include/bootutil/enc_key.h
  boot/bootutil/src/encrypted.c
  boot/cypress/MCUBootApp/keys.c
  boot/mbed/app_enc_keys.c
  boot/zephyr/keys.c
  ci/mynewt_keys/enc_kw/src/keys.c
  ci/mynewt_keys/enc_rsa/src/keys.c
  sim/mcuboot-sys/csupport/keys.c
Labels: Hotfix

#2002 boot: Add missing boot_enc_init
  boot/bootutil/src/loader.c
Labels: crypto

#2010 boot: Move encryption context invalidation to boot_enc_drop.
  boot/bootutil/src/encrypted.c
Labels: crypto

#1994 imgtool: Bump cryptography library version
  scripts/requirements.txt
  scripts/setup.py
Labels: area: imgtool, crypto

#2004 boot: Change boot_enc_load to take slot number instead of image
  boot/boot_serial/src/boot_serial_encryption.c
  boot/bootutil/include/bootutil/enc_key.h
  boot/bootutil/src/encrypted.c
  boot/bootutil/src/loader.c
Labels: crypto

#2014 boot: Reduce repeating code in boot_decrypt_and_copy_image_to_sram
  boot/bootutil/src/loader.c
Labels: crypto
